# Extra autostart processes
# exec-once = uwsm app -- my-service

# for Workspace 1
exec-once = uwsm app -- spotify
exec-once = uwsm app -- gio launch .local/share/applications/Gmail.desktop
exec-once = uwsm app -- gio launch .local/share/applications/"Google Calendar.desktop"

# for Workspace 2
exec-once = uwsm app -- gio launch .local/share/applications/"Home Assistant.desktop"
exec-once = uwsm app -- gio launch .local/share/applications/Kubernetes.desktop
exec-once = uwsm app -- gio launch .local/share/applications/FreshRSS.desktop

# for Workspace 3
exec-once = uwsm app -- firefox

# for Workspace 4
exec-once = uwsm app -- gio launch .local/share/applications/YouTube.desktop

# for Workspace 5
exec-once = uwsm app -- $terminal --working-directory=$HOME

# for Workspace 6
exec-once = uwsm app -- gio launch .local/share/applications/"Let's Go Further.desktop"

# for Workspace 7
exec-once = uwsm app -- microsoft-edge-stable

# for notification bar 
exec-once = uwsm app -- solaar -w hide

# rearrange startup applications
exec-once = /home/tuomo/.local/share/scripts/clean-workspaces-startup

# Reload plugins 
exec-once = hyprpm reload
