# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = spotify
exec-once = firefox
exec-once = uwsm app -- gio launch .local/share/applications/Home\ Assistant.desktop
exec-once = uwsm app -- gio launch .local/share/applications/Kubernetes.desktop
exec-once = uwsm app -- gio launch .local/share/applications/FreshRSS.desktop
exec-once = uwsm app -- gio launch .local/share/applications/"Let's Go Further.desktop"
exec-once = $terminal --working-directory=$HOME
exec-once = solaar -w hide
exec-once = /home/tuomo/.local/share/scripts/clean-workspaces
