# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # kb_layout = us,dk,eu
  kb_layout = fi

  # Commented kb_options out as I don't know how to use compose key and I don't have need for multiple keyboard layouts
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # Use caps lock as compose-key
  kb_options = # compose:caps,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Window is focused with mouse only if click
  follow_mouse = 0
  float_switch_override_focus = 0

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  # Commented touchpad out as I use desktop
  # touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    # scroll_factor = 0.4
  # }
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, tag:terminal

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace
