# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master

    # Enable Hyprscrolling
    layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

plugin {
    hyprscrolling {
        column_width = 0.49
        fullscreen_on_one_column = true
        focus_fit_method = 1
        explicit_column_widths = 0.33, 0.495, 0.66, 0.99
    }
    hyprexpo {
        columns = 4 
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = first 1 # center current [center/first] [workspace] e.g. first 1 or center m+1
        gesture_distance = 300 # how far is the "max" for the gesture
    }
}

